apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: cst
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: cst/auth-service:prod
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cst-config
                  key: AUTH_PORT
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: cst-config
                  key: MONGODB_URI_AUTH
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cst-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: cst
spec:
  selector:
    app: auth-service
  ports:
    - port: 5001
      targetPort: 5001
