apiVersion: v1
kind: ConfigMap
metadata:
  name: cst-config
  namespace: cst
data:
  AUTH_PORT: "5001"
  TICKET_PORT: "5000"
  SUPPORT_PORT: "5002"
  NOTIFICATION_PORT: "5003"
  MONGODB_URI_AUTH: "mongodb://mongodb:27017/cstAuthProd"
  MONGODB_URI_TICKET: "mongodb://mongodb:27017/ticketDBProd"
  MONGODB_URI_NOTIFICATION: "mongodb://mongodb:27017/cstNotificationsProd"
