apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - mongodb.yaml
  - auth-service.yaml
  - ticket-service.yaml
  - support-service.yaml
  - notification-service.yaml
  - frontend.yaml
