apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runtime-config.yaml
  - mongo.yaml
  - backend-auth.yaml
  - backend-ticket.yaml
  - backend-notification.yaml
  - backend-support.yaml
  - frontend.yaml
commonLabels:
  stack: customer-support-tickets
