apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customer-support-production
resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
patches:
  - path: patch-config.yaml
commonLabels:
  environment: production
